[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@solady=lib/solady/src/',
    '@modular-contracts/=lib/modular-contracts/src/',
]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config